# product_homepage:
#     path:     /
#     defaults: { _controller: ProductBundle:Default:index }

index:
    path:     /
    defaults: { _controller: ProductBundle:ProductController:index }


create_product:
  path:  /create_product
  defaults: {_controller: ProductBundle:ProductController:formCreaProduc}


load_product:
  path: /load-producto/{fatherId}
  defaults: {_controller: ProductBundle:ProductController:laodProduct }
  methods:  [GET]

save_product:
  path: /save-product
  defaults: {_controller: ProductBundle:ProductController:saveProduct }
  methods:  [POST]
